/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.FlowLayout;
import java.awt.Font;
import java.awt.LayoutManager;
import java.awt.event.ActionListener;
import javax.swing.JColorChooser;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import model.UrRulesModel;

/**
 *
 * @author Jimena Gdur
 */
public class MainMenuViewOld extends javax.swing.JPanel {

    /**
     * Creates new form MainMenuViewJPanel
     */
    public MainMenuViewOld() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        colorButton = new javax.swing.JButton();
        gameName = new javax.swing.JLabel();
        colorButton1 = new javax.swing.JButton();
        boxWithChosenColor = new javax.swing.JPanel();
        rulesButton = new javax.swing.JButton();

        colorButton.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        colorButton.setText("Choose a color");
        colorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colorButtonActionPerformed(evt);
            }
        });

        gameName.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        gameName.setText("Royal Game Of Ur");

        colorButton1.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        colorButton1.setText("Choose a color");
        colorButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colorButton1ActionPerformed(evt);
            }
        });

        boxWithChosenColor.setBackground(new java.awt.Color(255, 0, 0));
        boxWithChosenColor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout boxWithChosenColorLayout = new javax.swing.GroupLayout(boxWithChosenColor);
        boxWithChosenColor.setLayout(boxWithChosenColorLayout);
        boxWithChosenColorLayout.setHorizontalGroup(
            boxWithChosenColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );
        boxWithChosenColorLayout.setVerticalGroup(
            boxWithChosenColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 101, Short.MAX_VALUE)
        );

        rulesButton.setFont(new java.awt.Font("Century Schoolbook", 1, 18)); // NOI18N
        rulesButton.setText("Game Rules");
        rulesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rulesButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addComponent(gameName, javax.swing.GroupLayout.DEFAULT_SIZE, 331, Short.MAX_VALUE)
                .addGap(116, 116, 116))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rulesButton)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(boxWithChosenColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(197, 197, 197)
                        .addComponent(colorButton1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(gameName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                .addComponent(colorButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(boxWithChosenColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(rulesButton)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void colorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colorButtonActionPerformed

    }//GEN-LAST:event_colorButtonActionPerformed

    private void colorButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colorButton1ActionPerformed

    }//GEN-LAST:event_colorButton1ActionPerformed

    private void rulesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rulesButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rulesButtonActionPerformed

public void addColorButtonClickListener(ActionListener listenForButton) {
        colorButton.addActionListener(listenForButton);
    }
    
    public void addRulesButtonClickListener(ActionListener listenForButton) {
        rulesButton.addActionListener(listenForButton);
    }
    
    public void chooseColor() {
        Color initialColor = Color.RED;    
        chosenColor = JColorChooser.showDialog(this,"Select a color", initialColor);
    }
    
    public void setColorChooser() {
        boxWithChosenColor.setBackground(chosenColor);
    }
    
    public Color getChoosenColor() {
        return chosenColor;
    }
    
    public void showRules() {
        UrRulesModel rules = new UrRulesModel();
        
        JFrame frame = new JFrame("Swing Tester");
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        
        JPanel panel = new JPanel();
        LayoutManager layout = new FlowLayout();
        panel.setLayout(layout);
        
        final JLabel title = new JLabel();
        title.setFont(new Font("Century Schoolbook", 1, 36));
        title.setText(rules.getRules()[0]);
        panel.add(title);
        
        for (int index = 1; index < rules.getLength(); index++) {
            final JLabel label = new JLabel();
            label.setFont(new Font("Century Schoolbook", 0, 18));
            label.setText(rules.getRules()[index]);
            panel.add(label);
        }
  
        frame.getContentPane().add(panel, BorderLayout.CENTER);
        
        frame.setSize(560, 200);      
        frame.setLocationRelativeTo(null);  
        frame.setVisible(true);
    }
    
    private Color chosenColor;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel boxWithChosenColor;
    private javax.swing.JButton colorButton;
    private javax.swing.JButton colorButton1;
    private javax.swing.JLabel gameName;
    private javax.swing.JButton rulesButton;
    // End of variables declaration//GEN-END:variables
}
