/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import javax.swing.JButton;

/**
 *
 * @author Jimena Gdur, Mauricio Palma
 */
public class MainMenu extends javax.swing.JPanel {
    
    /**
     * Creates new form MainMenuViewJPanel
     */
    public MainMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popupMenu1 = new java.awt.PopupMenu();
        gameName = new javax.swing.JLabel();
        loadGameButton = new javax.swing.JButton();
        startNewGameButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        rulesButton = new javax.swing.JButton();

        popupMenu1.setLabel("popupMenu1");

        gameName.setFont(new java.awt.Font("Century Gothic", 1, 48)); // NOI18N
        gameName.setText("Royal Game Of Ur");

        loadGameButton.setBackground(new java.awt.Color(44, 37, 37));
        loadGameButton.setFont(new java.awt.Font("Century Schoolbook", 1, 24)); // NOI18N
        loadGameButton.setForeground(new java.awt.Color(255, 255, 255));
        loadGameButton.setText("LOAD GAME");
        loadGameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadGameButtonActionPerformed(evt);
            }
        });

        startNewGameButton.setBackground(new java.awt.Color(44, 37, 37));
        startNewGameButton.setFont(new java.awt.Font("Century Schoolbook", 1, 24)); // NOI18N
        startNewGameButton.setForeground(new java.awt.Color(255, 255, 255));
        startNewGameButton.setText("NEW GAME");
        startNewGameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startNewGameButtonActionPerformed(evt);
            }
        });

        exitButton.setBackground(new java.awt.Color(44, 37, 37));
        exitButton.setFont(new java.awt.Font("Century Schoolbook", 1, 24)); // NOI18N
        exitButton.setForeground(new java.awt.Color(255, 255, 255));
        exitButton.setText("EXIT");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        rulesButton.setBackground(new java.awt.Color(44, 37, 37));
        rulesButton.setFont(new java.awt.Font("Century Schoolbook", 1, 24)); // NOI18N
        rulesButton.setForeground(new java.awt.Color(255, 255, 255));
        rulesButton.setText("RULES");
        rulesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rulesButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(317, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rulesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(loadGameButton, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(startNewGameButton, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gameName))
                .addGap(310, 310, 310))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addComponent(gameName)
                .addGap(98, 98, 98)
                .addComponent(startNewGameButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(loadGameButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(rulesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(117, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void loadGameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadGameButtonActionPerformed

    }//GEN-LAST:event_loadGameButtonActionPerformed

    private void startNewGameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startNewGameButtonActionPerformed

    }//GEN-LAST:event_startNewGameButtonActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitButtonActionPerformed

    private void rulesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rulesButtonActionPerformed

    }//GEN-LAST:event_rulesButtonActionPerformed

    /* Button getters */
    public JButton getStartNewGameButton(){
       return startNewGameButton;
    }
    
    public JButton getLoadFormerGameButton(){
       return loadGameButton;
    }
    
    public JButton getShowRulesButton(){
        return rulesButton;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton exitButton;
    private javax.swing.JLabel gameName;
    private javax.swing.JButton loadGameButton;
    private java.awt.PopupMenu popupMenu1;
    private javax.swing.JButton rulesButton;
    private javax.swing.JButton startNewGameButton;
    // End of variables declaration//GEN-END:variables
}
