/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import java.awt.Color;
import java.awt.Image;
import java.awt.event.MouseListener;
import java.awt.image.BufferedImage;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author Ryzen
 */
public class MainGameView extends javax.swing.JPanel {
    private final static int ROWS = 8;
    private final static int COLUMNS = 3;

    private JLabel tilesArray[][] = new JLabel[ROWS][COLUMNS];
    /**
     * Creates new form MainGame
     */
    public MainGameView() throws IOException {
        initComponents();
        initializeTilesArray();
        makeUrBoard();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SaveButton = new javax.swing.JButton();
        rulesButton = new javax.swing.JButton();
        playerTurnLabel = new javax.swing.JLabel();
        Player1Panel = new javax.swing.JPanel();
        playerLabel = new javax.swing.JLabel();
        PlayerName = new java.awt.Label();
        PlayerScore = new javax.swing.JLabel();
        PlayerScoreTitle = new javax.swing.JLabel();
        inventoryTitle2 = new javax.swing.JLabel();
        firstPlayerPiece3 = new javax.swing.JButton();
        firstPlayerPiece5 = new javax.swing.JButton();
        firstPlayerPiece6 = new javax.swing.JButton();
        firstPlayerPiece4 = new javax.swing.JButton();
        firstPlayerPiece2 = new javax.swing.JButton();
        firstPlayerPiece1 = new javax.swing.JButton();
        firstPlayerPiece7 = new javax.swing.JButton();
        DicePanel = new javax.swing.JPanel();
        dice1 = new javax.swing.JLabel();
        dice2 = new javax.swing.JLabel();
        dice3 = new javax.swing.JLabel();
        dice4 = new javax.swing.JLabel();
        throwDiceButton = new javax.swing.JButton();
        moves = new javax.swing.JLabel();
        Player2Panel = new javax.swing.JPanel();
        playerLabel1 = new javax.swing.JLabel();
        PlayerName2 = new java.awt.Label();
        PlayerScore2 = new javax.swing.JLabel();
        PlayerScoreTitle2 = new javax.swing.JLabel();
        inventoryTitle3 = new javax.swing.JLabel();
        secondPlayerPiece3 = new javax.swing.JButton();
        secondPlayerPiece5 = new javax.swing.JButton();
        secondPlayerPiece6 = new javax.swing.JButton();
        secondPlayerPiece4 = new javax.swing.JButton();
        secondPlayerPiece2 = new javax.swing.JButton();
        secondPlayerPiece1 = new javax.swing.JButton();
        secondPlayerPiece7 = new javax.swing.JButton();
        boardGamePanel = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));

        SaveButton.setBackground(new java.awt.Color(44, 37, 37));
        SaveButton.setFont(new java.awt.Font("Century Schoolbook", 1, 24)); // NOI18N
        SaveButton.setForeground(new java.awt.Color(255, 255, 255));
        SaveButton.setText("SAVE AND EXIT");
        SaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveButtonActionPerformed(evt);
            }
        });

        rulesButton.setBackground(new java.awt.Color(44, 37, 37));
        rulesButton.setFont(new java.awt.Font("Century Schoolbook", 1, 24)); // NOI18N
        rulesButton.setForeground(new java.awt.Color(255, 255, 255));
        rulesButton.setText("GAME RULES");
        rulesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rulesButtonActionPerformed(evt);
            }
        });

        playerTurnLabel.setFont(new java.awt.Font("Century Schoolbook", 1, 24)); // NOI18N
        playerTurnLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        playerTurnLabel.setText("Player 1's turn");

        Player1Panel.setBackground(new java.awt.Color(255, 255, 255));
        Player1Panel.setPreferredSize(new java.awt.Dimension(350, 700));

        playerLabel.setFont(new java.awt.Font("Century Schoolbook", 1, 24)); // NOI18N
        playerLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        playerLabel.setText("Player 1");

        PlayerName.setAlignment(java.awt.Label.CENTER);
        PlayerName.setFont(new java.awt.Font("Century Schoolbook", 0, 18)); // NOI18N
        PlayerName.setText("label1");

        PlayerScore.setFont(new java.awt.Font("Century Schoolbook", 0, 24)); // NOI18N
        PlayerScore.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PlayerScore.setText("0");

        PlayerScoreTitle.setFont(new java.awt.Font("Century Schoolbook", 1, 24)); // NOI18N
        PlayerScoreTitle.setText("Score");

        inventoryTitle2.setFont(new java.awt.Font("Century Schoolbook", 0, 18)); // NOI18N
        inventoryTitle2.setText("Pieces Left");

        firstPlayerPiece3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/blueCircle.png"))); // NOI18N
        firstPlayerPiece3.setBorder(null);
        firstPlayerPiece3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstPlayerPiece3ActionPerformed(evt);
            }
        });

        firstPlayerPiece5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/blueCircle.png"))); // NOI18N
        firstPlayerPiece5.setBorder(null);
        firstPlayerPiece5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstPlayerPiece5ActionPerformed(evt);
            }
        });

        firstPlayerPiece6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/blueCircle.png"))); // NOI18N
        firstPlayerPiece6.setBorder(null);
        firstPlayerPiece6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstPlayerPiece6ActionPerformed(evt);
            }
        });

        firstPlayerPiece4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/blueCircle.png"))); // NOI18N
        firstPlayerPiece4.setBorder(null);
        firstPlayerPiece4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstPlayerPiece4ActionPerformed(evt);
            }
        });

        firstPlayerPiece2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/blueCircle.png"))); // NOI18N
        firstPlayerPiece2.setBorder(null);
        firstPlayerPiece2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstPlayerPiece2ActionPerformed(evt);
            }
        });

        firstPlayerPiece1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/blueCircle.png"))); // NOI18N
        firstPlayerPiece1.setBorder(null);
        firstPlayerPiece1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstPlayerPiece1ActionPerformed(evt);
            }
        });

        firstPlayerPiece7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/blueCircle.png"))); // NOI18N
        firstPlayerPiece7.setBorder(null);
        firstPlayerPiece7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstPlayerPiece7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Player1PanelLayout = new javax.swing.GroupLayout(Player1Panel);
        Player1Panel.setLayout(Player1PanelLayout);
        Player1PanelLayout.setHorizontalGroup(
            Player1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Player1PanelLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(Player1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Player1PanelLayout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(Player1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PlayerName, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(playerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(Player1PanelLayout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(inventoryTitle2))
                    .addGroup(Player1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(Player1PanelLayout.createSequentialGroup()
                            .addComponent(PlayerScoreTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(PlayerScore, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Player1PanelLayout.createSequentialGroup()
                            .addGroup(Player1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(firstPlayerPiece3)
                                .addComponent(firstPlayerPiece2)
                                .addComponent(firstPlayerPiece1))
                            .addGap(18, 18, 18)
                            .addComponent(firstPlayerPiece4)
                            .addGap(18, 18, 18)
                            .addGroup(Player1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(firstPlayerPiece6)
                                .addComponent(firstPlayerPiece5)
                                .addComponent(firstPlayerPiece7))
                            .addGap(72, 72, 72))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Player1PanelLayout.setVerticalGroup(
            Player1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Player1PanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(playerLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PlayerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(inventoryTitle2)
                .addGap(18, 18, 18)
                .addGroup(Player1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(firstPlayerPiece3)
                    .addComponent(firstPlayerPiece4)
                    .addComponent(firstPlayerPiece5))
                .addGap(18, 18, 18)
                .addGroup(Player1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(firstPlayerPiece6)
                    .addComponent(firstPlayerPiece2))
                .addGap(18, 18, 18)
                .addGroup(Player1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(firstPlayerPiece7)
                    .addComponent(firstPlayerPiece1))
                .addGap(54, 54, 54)
                .addGroup(Player1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PlayerScoreTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PlayerScore))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        dice1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/result_0_1.png"))); // NOI18N
        dice1.setText("dice1");

        dice2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/result_0_1.png"))); // NOI18N
        dice2.setText("dice2");

        dice3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/result_0_1.png"))); // NOI18N
        dice3.setText("dice3");

        dice4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/result_0_1.png"))); // NOI18N
        dice4.setText("dice4");

        throwDiceButton.setBackground(new java.awt.Color(44, 37, 37));
        throwDiceButton.setFont(new java.awt.Font("Century Schoolbook", 1, 18)); // NOI18N
        throwDiceButton.setForeground(new java.awt.Color(255, 255, 255));
        throwDiceButton.setText("THROW DICE");
        throwDiceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                throwDiceButtonActionPerformed(evt);
            }
        });

        moves.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        moves.setText("Number of moves");

        javax.swing.GroupLayout DicePanelLayout = new javax.swing.GroupLayout(DicePanel);
        DicePanel.setLayout(DicePanelLayout);
        DicePanelLayout.setHorizontalGroup(
            DicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DicePanelLayout.createSequentialGroup()
                .addGroup(DicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DicePanelLayout.createSequentialGroup()
                        .addComponent(dice1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dice2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dice3, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dice4, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(DicePanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(throwDiceButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(moves)))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        DicePanelLayout.setVerticalGroup(
            DicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DicePanelLayout.createSequentialGroup()
                .addGroup(DicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dice1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dice2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dice3, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dice4, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(DicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(throwDiceButton)
                    .addComponent(moves))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        Player2Panel.setBackground(new java.awt.Color(255, 255, 255));
        Player2Panel.setPreferredSize(new java.awt.Dimension(350, 700));

        playerLabel1.setFont(new java.awt.Font("Century Schoolbook", 1, 24)); // NOI18N
        playerLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        playerLabel1.setText("Player 2");

        PlayerName2.setAlignment(java.awt.Label.CENTER);
        PlayerName2.setFont(new java.awt.Font("Century Schoolbook", 0, 18)); // NOI18N
        PlayerName2.setText("label1");

        PlayerScore2.setFont(new java.awt.Font("Century Schoolbook", 0, 24)); // NOI18N
        PlayerScore2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PlayerScore2.setText("0");

        PlayerScoreTitle2.setFont(new java.awt.Font("Century Schoolbook", 1, 24)); // NOI18N
        PlayerScoreTitle2.setText("Score");

        inventoryTitle3.setFont(new java.awt.Font("Century Schoolbook", 0, 18)); // NOI18N
        inventoryTitle3.setText("Pieces Left");

        secondPlayerPiece3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/redCircle.png"))); // NOI18N
        secondPlayerPiece3.setBorder(null);
        secondPlayerPiece3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                secondPlayerPiece3ActionPerformed(evt);
            }
        });

        secondPlayerPiece5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/redCircle.png"))); // NOI18N
        secondPlayerPiece5.setBorder(null);
        secondPlayerPiece5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                secondPlayerPiece5ActionPerformed(evt);
            }
        });

        secondPlayerPiece6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/redCircle.png"))); // NOI18N
        secondPlayerPiece6.setBorder(null);
        secondPlayerPiece6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                secondPlayerPiece6ActionPerformed(evt);
            }
        });

        secondPlayerPiece4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/redCircle.png"))); // NOI18N
        secondPlayerPiece4.setBorder(null);
        secondPlayerPiece4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                secondPlayerPiece4ActionPerformed(evt);
            }
        });

        secondPlayerPiece2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/redCircle.png"))); // NOI18N
        secondPlayerPiece2.setBorder(null);
        secondPlayerPiece2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                secondPlayerPiece2ActionPerformed(evt);
            }
        });

        secondPlayerPiece1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/redCircle.png"))); // NOI18N
        secondPlayerPiece1.setBorder(null);
        secondPlayerPiece1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                secondPlayerPiece1ActionPerformed(evt);
            }
        });

        secondPlayerPiece7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/redCircle.png"))); // NOI18N
        secondPlayerPiece7.setBorder(null);
        secondPlayerPiece7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                secondPlayerPiece7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Player2PanelLayout = new javax.swing.GroupLayout(Player2Panel);
        Player2Panel.setLayout(Player2PanelLayout);
        Player2PanelLayout.setHorizontalGroup(
            Player2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Player2PanelLayout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(Player2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(playerLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PlayerName2, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(Player2PanelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(Player2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(Player2PanelLayout.createSequentialGroup()
                        .addComponent(PlayerScoreTitle2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(PlayerScore2, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Player2PanelLayout.createSequentialGroup()
                        .addGroup(Player2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(inventoryTitle3)
                            .addGroup(Player2PanelLayout.createSequentialGroup()
                                .addGroup(Player2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(secondPlayerPiece3)
                                    .addComponent(secondPlayerPiece2)
                                    .addComponent(secondPlayerPiece1))
                                .addGap(18, 18, 18)
                                .addComponent(secondPlayerPiece4)))
                        .addGap(18, 18, 18)
                        .addGroup(Player2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(secondPlayerPiece6)
                            .addComponent(secondPlayerPiece5)
                            .addComponent(secondPlayerPiece7))))
                .addGap(0, 29, Short.MAX_VALUE))
        );
        Player2PanelLayout.setVerticalGroup(
            Player2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Player2PanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(playerLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PlayerName2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(inventoryTitle3)
                .addGap(18, 18, 18)
                .addGroup(Player2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(secondPlayerPiece3)
                    .addComponent(secondPlayerPiece4)
                    .addComponent(secondPlayerPiece5))
                .addGap(18, 18, 18)
                .addGroup(Player2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(secondPlayerPiece6)
                    .addComponent(secondPlayerPiece2))
                .addGap(18, 18, 18)
                .addGroup(Player2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(secondPlayerPiece7)
                    .addComponent(secondPlayerPiece1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addGroup(Player2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PlayerScoreTitle2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PlayerScore2)))
        );

        javax.swing.GroupLayout boardGamePanelLayout = new javax.swing.GroupLayout(boardGamePanel);
        boardGamePanel.setLayout(boardGamePanelLayout);
        boardGamePanelLayout.setHorizontalGroup(
            boardGamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 336, Short.MAX_VALUE)
        );
        boardGamePanelLayout.setVerticalGroup(
            boardGamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 715, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Player1Panel, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(DicePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(boardGamePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rulesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SaveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(33, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Player2Panel, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(playerTurnLabel)
                .addGap(413, 413, 413))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(playerTurnLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Player1Panel, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(DicePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(boardGamePanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Player2Panel, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                        .addComponent(rulesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(SaveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void SaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SaveButtonActionPerformed

    private void rulesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rulesButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rulesButtonActionPerformed

    private void firstPlayerPiece3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstPlayerPiece3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstPlayerPiece3ActionPerformed

    private void firstPlayerPiece5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstPlayerPiece5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstPlayerPiece5ActionPerformed

    private void firstPlayerPiece6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstPlayerPiece6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstPlayerPiece6ActionPerformed

    private void firstPlayerPiece4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstPlayerPiece4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstPlayerPiece4ActionPerformed

    private void firstPlayerPiece2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstPlayerPiece2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstPlayerPiece2ActionPerformed

    private void firstPlayerPiece1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstPlayerPiece1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstPlayerPiece1ActionPerformed

    private void firstPlayerPiece7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstPlayerPiece7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstPlayerPiece7ActionPerformed

    private void secondPlayerPiece3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_secondPlayerPiece3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_secondPlayerPiece3ActionPerformed

    private void secondPlayerPiece5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_secondPlayerPiece5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_secondPlayerPiece5ActionPerformed

    private void secondPlayerPiece6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_secondPlayerPiece6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_secondPlayerPiece6ActionPerformed

    private void secondPlayerPiece4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_secondPlayerPiece4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_secondPlayerPiece4ActionPerformed

    private void secondPlayerPiece2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_secondPlayerPiece2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_secondPlayerPiece2ActionPerformed

    private void secondPlayerPiece1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_secondPlayerPiece1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_secondPlayerPiece1ActionPerformed

    private void secondPlayerPiece7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_secondPlayerPiece7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_secondPlayerPiece7ActionPerformed

    private void throwDiceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_throwDiceButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_throwDiceButtonActionPerformed

    public void addMouseListener(MouseListener listenForMouse) {
        addMouseListener(listenForMouse);
    }
    
    public JLabel getLabel(int row, int column){
        System.out.println("Returning label");
        return tilesArray[row][column];
    }
    
    private void  initializeTilesArray(){
        int intialXGap = 39;
        int intialYGap = 18;
        int horizontalGapTuning = 89;
        int verticalGapTuning = horizontalGapTuning - 50;
        int verticaOffset = horizontalGapTuning - 2;
        for (int row = 0; row < ROWS; row++) {
            for (int column = 0; column < COLUMNS; column++) 
            {
                tilesArray[row][column] = new JLabel();
                tilesArray[row][column].setBackground(Color.decode("#2D3553"));
                tilesArray[row][column].setOpaque(true);
                tilesArray[row][column].setBounds(intialXGap, intialYGap, 80, 80);
                boardGamePanel.add(tilesArray[row][column]);
                //tilesArray[row][column].addMouseListener(new TileMouseListener(tilesArray[row][column], row, column));
                intialXGap += horizontalGapTuning;
            }
            intialXGap = verticalGapTuning;
            intialYGap += verticaOffset;
        }
    }
    
    private void makeUrBoard() throws IOException{
        BufferedImage image = ImageIO.read(getClass().getResourceAsStream("/images/icon2_rounded.png"));
        ImageIcon roseIcon = new ImageIcon(image);
        Image temporalImage = roseIcon.getImage();
        Image resizedImage = temporalImage.getScaledInstance(80, 80,  java.awt.Image.SCALE_SMOOTH);
        roseIcon = new ImageIcon(resizedImage);
        tilesArray[4][0].show(false);
        tilesArray[5][0].show(false);
        tilesArray[4][2].show(false);
        tilesArray[5][2].show(false);
        tilesArray[0][0].setIcon(roseIcon);
        tilesArray[0][2].setIcon(roseIcon);
        tilesArray[3][1].setIcon(roseIcon);
        tilesArray[6][0].setIcon(roseIcon);
        tilesArray[6][2].setIcon(roseIcon);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DicePanel;
    private javax.swing.JPanel Player1Panel;
    private javax.swing.JPanel Player2Panel;
    private java.awt.Label PlayerName;
    private java.awt.Label PlayerName2;
    private javax.swing.JLabel PlayerScore;
    private javax.swing.JLabel PlayerScore2;
    private javax.swing.JLabel PlayerScoreTitle;
    private javax.swing.JLabel PlayerScoreTitle2;
    private javax.swing.JButton SaveButton;
    private javax.swing.JPanel boardGamePanel;
    private javax.swing.JLabel dice1;
    private javax.swing.JLabel dice2;
    private javax.swing.JLabel dice3;
    private javax.swing.JLabel dice4;
    private javax.swing.JButton firstPlayerPiece1;
    private javax.swing.JButton firstPlayerPiece2;
    private javax.swing.JButton firstPlayerPiece3;
    private javax.swing.JButton firstPlayerPiece4;
    private javax.swing.JButton firstPlayerPiece5;
    private javax.swing.JButton firstPlayerPiece6;
    private javax.swing.JButton firstPlayerPiece7;
    private javax.swing.JLabel inventoryTitle2;
    private javax.swing.JLabel inventoryTitle3;
    private javax.swing.JLabel moves;
    private javax.swing.JLabel playerLabel;
    private javax.swing.JLabel playerLabel1;
    private javax.swing.JLabel playerTurnLabel;
    private javax.swing.JButton rulesButton;
    private javax.swing.JButton secondPlayerPiece1;
    private javax.swing.JButton secondPlayerPiece2;
    private javax.swing.JButton secondPlayerPiece3;
    private javax.swing.JButton secondPlayerPiece4;
    private javax.swing.JButton secondPlayerPiece5;
    private javax.swing.JButton secondPlayerPiece6;
    private javax.swing.JButton secondPlayerPiece7;
    private javax.swing.JButton throwDiceButton;
    // End of variables declaration//GEN-END:variables

}

