/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.FlowLayout;
import java.awt.Font;
import java.awt.Image;
import java.awt.LayoutManager;
import java.awt.event.ActionListener;
import java.awt.event.MouseListener;
import java.awt.image.BufferedImage;
import java.io.FileInputStream;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import model.UrRulesModel;

/**
 *
 * @author Ryzen
 */
public class MainGameView extends javax.swing.JPanel {
    private final static int ROWS = 8;
    private final static int COLUMNS = 3;
    private JLabel tilesArray[][] = new JLabel[ROWS][COLUMNS];
    private JLabel diceLabelArray [];
    private ImageIcon noScoreDiceState;
    private ImageIcon scoreDiceState;
    
    private final static Color BLUE = new Color (0,102,255);
    private final static Color BROWN = new Color (102,51,0);
    private final static Color GREEN = new Color (102,204,0);
    private final static Color PURPLE = new Color (102,0,102);
    private final static Color RED = new Color (255,0,0);
    private final static Color YELLOW = new Color (255,204,0);
    
    
    /**
     * Creates new form MainGame
     */
    public MainGameView() throws IOException {
        initComponents();
        initializeTilesArray();
        makeUrBoard();
        makeDices();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        saveAndLeaveButton = new javax.swing.JButton();
        rulesButton = new javax.swing.JButton();
        playerTurnLabel = new javax.swing.JLabel();
        Player1Panel = new javax.swing.JPanel();
        firstPlayerTitleLabel = new javax.swing.JLabel();
        firstPlayerLabelName = new java.awt.Label();
        PlayerScore = new javax.swing.JLabel();
        PlayerScoreTitle = new javax.swing.JLabel();
        inventoryTitle2 = new javax.swing.JLabel();
        pieceLabelFirstPlayer1 = new javax.swing.JLabel();
        pieceLabelFirstPlayer2 = new javax.swing.JLabel();
        pieceLabelFirstPlayer3 = new javax.swing.JLabel();
        pieceLabelFirstPlayer4 = new javax.swing.JLabel();
        pieceLabelFirstPlayer5 = new javax.swing.JLabel();
        pieceLabelFirstPlayer6 = new javax.swing.JLabel();
        pieceLabelFirstPlayer7 = new javax.swing.JLabel();
        Player2Panel = new javax.swing.JPanel();
        secondPlayerTitleLabel = new javax.swing.JLabel();
        secondPlayerLabelName = new java.awt.Label();
        PlayerScore2 = new javax.swing.JLabel();
        PlayerScoreTitle2 = new javax.swing.JLabel();
        inventoryTitle3 = new javax.swing.JLabel();
        pieceLabelSecondPlayer1 = new javax.swing.JLabel();
        pieceLabelSecondPlayer2 = new javax.swing.JLabel();
        pieceLabelSecondPlayer3 = new javax.swing.JLabel();
        pieceLabelSecondPlayer4 = new javax.swing.JLabel();
        pieceLabelSecondPlayer5 = new javax.swing.JLabel();
        pieceLabelSecondPlayer6 = new javax.swing.JLabel();
        pieceLabelSecondPlayer7 = new javax.swing.JLabel();
        boardGamePanel = new javax.swing.JPanel();
        dicePanel = new javax.swing.JPanel();
        dice4 = new javax.swing.JLabel();
        dice3 = new javax.swing.JLabel();
        dice2 = new javax.swing.JLabel();
        dice1 = new javax.swing.JLabel();
        throwDiceButton = new javax.swing.JButton();
        moves = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        saveAndLeaveButton.setBackground(new java.awt.Color(44, 37, 37));
        saveAndLeaveButton.setFont(new java.awt.Font("Century Schoolbook", 1, 24)); // NOI18N
        saveAndLeaveButton.setForeground(new java.awt.Color(255, 255, 255));
        saveAndLeaveButton.setText("SAVE AND EXIT");
        saveAndLeaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveAndLeaveButtonActionPerformed(evt);
            }
        });

        rulesButton.setBackground(new java.awt.Color(44, 37, 37));
        rulesButton.setFont(new java.awt.Font("Century Schoolbook", 1, 24)); // NOI18N
        rulesButton.setForeground(new java.awt.Color(255, 255, 255));
        rulesButton.setText("GAME RULES");
        rulesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rulesButtonActionPerformed(evt);
            }
        });

        playerTurnLabel.setFont(new java.awt.Font("Century Schoolbook", 1, 24)); // NOI18N
        playerTurnLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        playerTurnLabel.setText("Player 1's turn");

        Player1Panel.setBackground(new java.awt.Color(255, 255, 255));
        Player1Panel.setPreferredSize(new java.awt.Dimension(350, 700));

        firstPlayerTitleLabel.setFont(new java.awt.Font("Century Schoolbook", 1, 24)); // NOI18N
        firstPlayerTitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        firstPlayerTitleLabel.setText("Player 1");

        firstPlayerLabelName.setAlignment(java.awt.Label.CENTER);
        firstPlayerLabelName.setFont(new java.awt.Font("Century Schoolbook", 0, 18)); // NOI18N
        firstPlayerLabelName.setText("label1");

        PlayerScore.setFont(new java.awt.Font("Century Schoolbook", 0, 24)); // NOI18N
        PlayerScore.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PlayerScore.setText("0");

        PlayerScoreTitle.setFont(new java.awt.Font("Century Schoolbook", 1, 24)); // NOI18N
        PlayerScoreTitle.setText("Score");

        inventoryTitle2.setFont(new java.awt.Font("Century Schoolbook", 0, 18)); // NOI18N
        inventoryTitle2.setText("Pieces Left");

        pieceLabelFirstPlayer1.setText("jLabel1");

        pieceLabelFirstPlayer2.setText("jLabel1");

        pieceLabelFirstPlayer3.setText("jLabel1");

        pieceLabelFirstPlayer4.setText("jLabel1");

        pieceLabelFirstPlayer5.setText("jLabel1");

        pieceLabelFirstPlayer6.setText("jLabel1");

        pieceLabelFirstPlayer7.setText("jLabel1");

        javax.swing.GroupLayout Player1PanelLayout = new javax.swing.GroupLayout(Player1Panel);
        Player1Panel.setLayout(Player1PanelLayout);
        Player1PanelLayout.setHorizontalGroup(
            Player1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Player1PanelLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(Player1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Player1PanelLayout.createSequentialGroup()
                        .addGroup(Player1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Player1PanelLayout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addGroup(Player1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(firstPlayerLabelName, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(firstPlayerTitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(Player1PanelLayout.createSequentialGroup()
                                .addGap(75, 75, 75)
                                .addComponent(inventoryTitle2)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(Player1PanelLayout.createSequentialGroup()
                        .addGroup(Player1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(Player1PanelLayout.createSequentialGroup()
                                .addGap(0, 5, Short.MAX_VALUE)
                                .addGroup(Player1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(pieceLabelFirstPlayer3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pieceLabelFirstPlayer4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pieceLabelFirstPlayer6, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(Player1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Player1PanelLayout.createSequentialGroup()
                                        .addComponent(pieceLabelFirstPlayer1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addGroup(Player1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(pieceLabelFirstPlayer2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(pieceLabelFirstPlayer5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(pieceLabelFirstPlayer7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(Player1PanelLayout.createSequentialGroup()
                                .addComponent(PlayerScoreTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(PlayerScore, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(38, Short.MAX_VALUE))))
        );
        Player1PanelLayout.setVerticalGroup(
            Player1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Player1PanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(firstPlayerTitleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(firstPlayerLabelName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(inventoryTitle2)
                .addGroup(Player1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Player1PanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(Player1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pieceLabelFirstPlayer4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pieceLabelFirstPlayer1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pieceLabelFirstPlayer2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pieceLabelFirstPlayer3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Player1PanelLayout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(pieceLabelFirstPlayer5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(Player1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pieceLabelFirstPlayer6, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pieceLabelFirstPlayer7, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(Player1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PlayerScoreTitle)
                    .addComponent(PlayerScore))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        Player2Panel.setBackground(new java.awt.Color(255, 255, 255));
        Player2Panel.setPreferredSize(new java.awt.Dimension(350, 700));

        secondPlayerTitleLabel.setFont(new java.awt.Font("Century Schoolbook", 1, 24)); // NOI18N
        secondPlayerTitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        secondPlayerTitleLabel.setText("Player 2");

        secondPlayerLabelName.setAlignment(java.awt.Label.CENTER);
        secondPlayerLabelName.setFont(new java.awt.Font("Century Schoolbook", 0, 18)); // NOI18N
        secondPlayerLabelName.setText("label1");

        PlayerScore2.setFont(new java.awt.Font("Century Schoolbook", 0, 24)); // NOI18N
        PlayerScore2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PlayerScore2.setText("0");

        PlayerScoreTitle2.setFont(new java.awt.Font("Century Schoolbook", 1, 24)); // NOI18N
        PlayerScoreTitle2.setText("Score");

        inventoryTitle3.setFont(new java.awt.Font("Century Schoolbook", 0, 18)); // NOI18N
        inventoryTitle3.setText("Pieces Left");

        pieceLabelSecondPlayer1.setText("jLabel1");

        pieceLabelSecondPlayer2.setText("jLabel1");

        pieceLabelSecondPlayer3.setText("jLabel1");

        pieceLabelSecondPlayer4.setText("jLabel1");

        pieceLabelSecondPlayer5.setText("jLabel1");

        pieceLabelSecondPlayer6.setText("jLabel1");

        pieceLabelSecondPlayer7.setText("jLabel1");

        javax.swing.GroupLayout Player2PanelLayout = new javax.swing.GroupLayout(Player2Panel);
        Player2Panel.setLayout(Player2PanelLayout);
        Player2PanelLayout.setHorizontalGroup(
            Player2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Player2PanelLayout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(Player2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(secondPlayerTitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(secondPlayerLabelName, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(Player2PanelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(Player2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(Player2PanelLayout.createSequentialGroup()
                        .addGroup(Player2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(pieceLabelSecondPlayer4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pieceLabelSecondPlayer1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pieceLabelSecondPlayer7, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(Player2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Player2PanelLayout.createSequentialGroup()
                                .addComponent(pieceLabelSecondPlayer6, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(Player2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pieceLabelSecondPlayer3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pieceLabelSecondPlayer5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(pieceLabelSecondPlayer2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(Player2PanelLayout.createSequentialGroup()
                        .addComponent(PlayerScoreTitle2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(PlayerScore2, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Player2PanelLayout.createSequentialGroup()
                        .addComponent(inventoryTitle3)
                        .addGap(88, 88, 88)))
                .addGap(0, 29, Short.MAX_VALUE))
        );
        Player2PanelLayout.setVerticalGroup(
            Player2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Player2PanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(secondPlayerTitleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(secondPlayerLabelName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(inventoryTitle3)
                .addGap(18, 18, 18)
                .addGroup(Player2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Player2PanelLayout.createSequentialGroup()
                        .addGroup(Player2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pieceLabelSecondPlayer1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pieceLabelSecondPlayer6, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pieceLabelSecondPlayer3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pieceLabelSecondPlayer4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Player2PanelLayout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(pieceLabelSecondPlayer5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(Player2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pieceLabelSecondPlayer7, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pieceLabelSecondPlayer2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addGroup(Player2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PlayerScoreTitle2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PlayerScore2)))
        );

        javax.swing.GroupLayout boardGamePanelLayout = new javax.swing.GroupLayout(boardGamePanel);
        boardGamePanel.setLayout(boardGamePanelLayout);
        boardGamePanelLayout.setHorizontalGroup(
            boardGamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 336, Short.MAX_VALUE)
        );
        boardGamePanelLayout.setVerticalGroup(
            boardGamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 715, Short.MAX_VALUE)
        );

        dice4.setText("dice4");

        dice3.setText("dice3");

        dice2.setText("dice2");

        dice1.setText("dice1");

        throwDiceButton.setBackground(new java.awt.Color(44, 37, 37));
        throwDiceButton.setFont(new java.awt.Font("Century Schoolbook", 1, 18)); // NOI18N
        throwDiceButton.setForeground(new java.awt.Color(255, 255, 255));
        throwDiceButton.setText("THROW DICE");
        throwDiceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                throwDiceButtonActionPerformed(evt);
            }
        });

        moves.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        moves.setText("Number of moves");

        javax.swing.GroupLayout dicePanelLayout = new javax.swing.GroupLayout(dicePanel);
        dicePanel.setLayout(dicePanelLayout);
        dicePanelLayout.setHorizontalGroup(
            dicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dicePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dicePanelLayout.createSequentialGroup()
                        .addComponent(dice1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dice2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dice3, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dice4, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(dicePanelLayout.createSequentialGroup()
                        .addComponent(throwDiceButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(moves)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        dicePanelLayout.setVerticalGroup(
            dicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dicePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dice1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dice2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dice3, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dice4, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(throwDiceButton)
                    .addComponent(moves))
                .addContainerGap(7, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Player1Panel, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(dicePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(boardGamePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rulesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(saveAndLeaveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(33, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Player2Panel, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(playerTurnLabel)
                .addGap(413, 413, 413))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(playerTurnLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(boardGamePanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(Player2Panel, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(rulesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(saveAndLeaveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(15, 15, 15)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Player1Panel, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                        .addComponent(dicePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void saveAndLeaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveAndLeaveButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saveAndLeaveButtonActionPerformed

    private void rulesButtonActionPerformed(java.awt.event.ActionEvent evt) {                                            
        UrRulesModel rules = new UrRulesModel();
        JFrame frame = new JFrame("Rules");        
        JPanel panel = new JPanel();
        LayoutManager layout = new FlowLayout();
        panel.setLayout(layout);     
        final JLabel title = new JLabel();
        title.setFont(new Font("Century Schoolbook", 1, 36));
        title.setText(rules.getRules()[0]);
        panel.add(title);    
        for (int index = 1; index < rules.getLength(); index++) {
            final JLabel label = new JLabel();
            label.setFont(new Font("Century Schoolbook", 0, 18));
            label.setText(rules.getRules()[index]);
            panel.add(label);
        }
        frame.getContentPane().add(panel, BorderLayout.CENTER);   
        frame.setSize(600, 420);      
        frame.setLocationRelativeTo(null);  
        frame.setVisible(true);
        frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }                                           

    private void throwDiceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_throwDiceButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_throwDiceButtonActionPerformed

    /* Main Panel Buttons */

    public void addSaveAndLeaveButtonClickListener(ActionListener listenForButton) {
        saveAndLeaveButton.addActionListener(listenForButton);
    }
    
    /*Load Images Methods*/
    
    private BufferedImage loadImagesForJarFile(String imageName) throws IOException{
        String generalPath = "/images/";
        String extensionName = ".png";
        String finalPath = generalPath+imageName+extensionName;
        BufferedImage image = ImageIO.read(getClass().getResourceAsStream(finalPath));  
        return image;
    }
    
    private BufferedImage loadImagesForIDEFile(String imageName) throws IOException{
        String generalPath = "images/";
        String extensionName = ".png";
        String finalPath = generalPath+imageName+extensionName;
        BufferedImage image = ImageIO.read(new FileInputStream(finalPath));   
        return image;
    }

    /* Main Board Methods  */
    private void makeUrBoard() throws IOException{
        try {
            /*For JAR FILE*/
            // BufferedImage image = loadImagesForJarFile("icon2_rounded");
            
            /*For NetBeans*/
            BufferedImage image = loadImagesForIDEFile("icon2_rounded");
            
            ImageIcon roseIcon = resizeImage(image, 80,80);
            tilesArray[4][0].show(false);
            tilesArray[5][0].show(false);
            tilesArray[4][2].show(false);
            tilesArray[5][2].show(false);
            tilesArray[0][0].setIcon(roseIcon);
            tilesArray[0][2].setIcon(roseIcon);
            tilesArray[3][1].setIcon(roseIcon);
            tilesArray[6][0].setIcon(roseIcon);
            tilesArray[6][2].setIcon(roseIcon);
        } catch (IOException e) {
            System.out.println("Rose icon not found");
        }
    }
    
    private void  initializeTilesArray(){
        int intialXGap = 39;
        int intialYGap = 18;
        int horizontalGapTuning = 89;
        int verticalGapTuning = horizontalGapTuning - 50;
        int verticaOffset = horizontalGapTuning - 2;
        for (int row = 0; row < ROWS; row++) {
            for (int column = 0; column < COLUMNS; column++) 
            {
                tilesArray[row][column] = new JLabel();
                tilesArray[row][column].setBackground(Color.decode("#2D3553"));
                tilesArray[row][column].setOpaque(true);
                tilesArray[row][column].setBounds(intialXGap, intialYGap, 80, 80);
                boardGamePanel.add(tilesArray[row][column]);
                intialXGap += horizontalGapTuning;
            }
            intialXGap = verticalGapTuning;
            intialYGap += verticaOffset;
        }
    }
    
    public JLabel getLabel(int row, int column){
        return tilesArray[row][column];
    }
    
    public void setNextPossibleLabel(int row, int column) {
        tilesArray[row][column].setBackground(Color.WHITE);
    }

    /* Color choose Pieces Feature */
    public void setFirstPlayerPieceColor(Color color) throws IOException {
        try {
            BufferedImage image = null;
            if (color.getRGB() == BLUE.getRGB()) {
                //image = loadImagesForJarFile("blue_piece_rbg");
                image = loadImagesForIDEFile("blue_piece_rbg");
            } else if (color.getRGB() == BROWN.getRGB()) {
                //image = loadImagesForJarFile("brown_piece_rbg");
                image = loadImagesForIDEFile("brown_piece_rbg");
            } else if (color.getRGB() == GREEN.getRGB()) {
                //image = loadImagesForJarFile("green_piece_rbg");
                image = loadImagesForIDEFile("green_piece_rbg");
            } else if (color.getRGB() == PURPLE.getRGB()) {
                //image = loadImagesForJarFile("purple_piece_rbg");
                image = loadImagesForIDEFile("purple_piece_rbg");
            } else if (color.getRGB() == RED.getRGB()) {
                //image = loadImagesForJarFile("red_piece_rbg");
                image = loadImagesForIDEFile("red_piece_rbg");
            } else if (color.getRGB() == YELLOW.getRGB()) {
                //image = loadImagesForJarFile("yellow_piece_rbg");
                image = loadImagesForIDEFile("yellow_piece_rbg");
            }
            ImageIcon colorIcon = resizeImage(image, 78, 78);
            modifiyFirstPlayerPieces(colorIcon);
            
        } catch (IOException e) {
            System.out.println("Color piece icon not found");
        }
    }
    
    public void setSecondPlayerPieceColor(Color color) throws IOException{
            try {
            BufferedImage image = null;
            if (color.getRGB() == BLUE.getRGB()) {
                //image = loadImagesForJarFile("blue_piece_rbg");
                image = loadImagesForIDEFile("blue_piece_rbg");
            } else if (color.getRGB() == BROWN.getRGB()) {
                //image = loadImagesForJarFile("brown_piece_rbg");
                image = loadImagesForIDEFile("brown_piece_rbg");
            } else if (color.getRGB() == GREEN.getRGB()) {
                //image = loadImagesForJarFile("green_piece_rbg");
                image = loadImagesForIDEFile("green_piece_rbg");
            } else if (color.getRGB() == PURPLE.getRGB()) {
                //image = loadImagesForJarFile("purple_piece_rbg");
                image = loadImagesForIDEFile("purple_piece_rbg");
            } else if (color.getRGB() == RED.getRGB()) {
                //image = loadImagesForJarFile("red_piece_rbg");
                image = loadImagesForIDEFile("red_piece_rbg");
            } else if (color.getRGB() == YELLOW.getRGB()) {
                //image = loadImagesForJarFile("yellow_piece_rbg");
                image = loadImagesForIDEFile("yellow_piece_rbg");
            }
            ImageIcon colorIcon = resizeImage(image, 78, 78);
            modifySecondPlayerPieces(colorIcon);
            
        } catch (IOException e) {
            System.out.println("Color piece icon not found");
        }
    }
    
    /* Main Frame Dices Feature */
    private void makeDices(){
        try{
            diceLabelArray = new JLabel[4];      
            /*For JAR file*/
            //BufferedImage diceState1Image = loadImagesForJarFile("result_0_1");
            //BufferedImage diceState2Image = loadImagesForJarFile("result_1_1");
            
            /*For NetBeans*/   
            BufferedImage diceState1Image = loadImagesForIDEFile("result_0_1");
            BufferedImage diceState2Image = loadImagesForIDEFile("result_1_1");

            noScoreDiceState = resizeImage(diceState1Image, 77, 77);
            scoreDiceState = resizeImage(diceState2Image, 77, 77 );
            diceLabelArray[0] = dice1;
            diceLabelArray[1] = dice2;
            diceLabelArray[2] = dice3;
            diceLabelArray[3] = dice4;
            dice1.setIcon(noScoreDiceState);
            dice2.setIcon(noScoreDiceState);
            dice3.setIcon(noScoreDiceState);
            dice4.setIcon(noScoreDiceState);
            
        } catch(IOException e){
            System.out.println("Dices images not found!");
        }
    }
    
    private ImageIcon resizeImage(BufferedImage diceState, int width, int height){
        ImageIcon diceStateIcon = new ImageIcon(diceState);
        Image temporalImage = diceStateIcon.getImage();
        Image resizedImage = temporalImage.getScaledInstance(width, height,  java.awt.Image.SCALE_SMOOTH);
        return new ImageIcon(resizedImage);
    }
    
    public void showThrow(int rollResult)
    {
        for(int index = 0; index < rollResult; index++){
            diceLabelArray[index].setIcon(scoreDiceState);
        }
    }
    
    public void cleanDice()
    {
         dice1.setIcon(noScoreDiceState);
         dice2.setIcon(noScoreDiceState);
         dice3.setIcon(noScoreDiceState);
         dice4.setIcon(noScoreDiceState);
    }
    
    public void setMoves(int rollResult)
    {
        String movesResult = String.valueOf(rollResult);
        moves.setText(movesResult);
    }
    
    public void addthrowDiceButtonClickListener(ActionListener listenForThrowDice)
    {
        throwDiceButton.addActionListener(listenForThrowDice); 
    }
    
    /* Mapping methods from logical matrix to graphical one */
    public void mapLogicalMatrix(){
        
    }
    
    /*Personalized match */
    public void setFirstPlayerNameToLabel(String name){
        firstPlayerLabelName.setText(name);
    }
    
    public void setSecondPlayerNameToLabel(String name){
        secondPlayerLabelName.setText(name);
    }
    
    private void modifiyFirstPlayerPieces(ImageIcon icon) {
        pieceLabelFirstPlayer1.setIcon(icon);
        pieceLabelFirstPlayer2.setIcon(icon);
        pieceLabelFirstPlayer3.setIcon(icon);
        pieceLabelFirstPlayer4.setIcon(icon);
        pieceLabelFirstPlayer5.setIcon(icon);
        pieceLabelFirstPlayer6.setIcon(icon);
        pieceLabelFirstPlayer7.setIcon(icon);
    }
    
    private void modifySecondPlayerPieces(ImageIcon icon)  {
        pieceLabelSecondPlayer1.setIcon(icon);
        pieceLabelSecondPlayer2.setIcon(icon);
        pieceLabelSecondPlayer3.setIcon(icon);
        pieceLabelSecondPlayer4.setIcon(icon);
        pieceLabelSecondPlayer5.setIcon(icon);
        pieceLabelSecondPlayer6.setIcon(icon);
        pieceLabelSecondPlayer7.setIcon(icon);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Player1Panel;
    private javax.swing.JPanel Player2Panel;
    private javax.swing.JLabel PlayerScore;
    private javax.swing.JLabel PlayerScore2;
    private javax.swing.JLabel PlayerScoreTitle;
    private javax.swing.JLabel PlayerScoreTitle2;
    private javax.swing.JPanel boardGamePanel;
    private javax.swing.JLabel dice1;
    private javax.swing.JLabel dice2;
    private javax.swing.JLabel dice3;
    private javax.swing.JLabel dice4;
    private javax.swing.JPanel dicePanel;
    private java.awt.Label firstPlayerLabelName;
    private javax.swing.JLabel firstPlayerTitleLabel;
    private javax.swing.JLabel inventoryTitle2;
    private javax.swing.JLabel inventoryTitle3;
    private javax.swing.JLabel moves;
    private javax.swing.JLabel pieceLabelFirstPlayer1;
    private javax.swing.JLabel pieceLabelFirstPlayer2;
    private javax.swing.JLabel pieceLabelFirstPlayer3;
    private javax.swing.JLabel pieceLabelFirstPlayer4;
    private javax.swing.JLabel pieceLabelFirstPlayer5;
    private javax.swing.JLabel pieceLabelFirstPlayer6;
    private javax.swing.JLabel pieceLabelFirstPlayer7;
    private javax.swing.JLabel pieceLabelSecondPlayer1;
    private javax.swing.JLabel pieceLabelSecondPlayer2;
    private javax.swing.JLabel pieceLabelSecondPlayer3;
    private javax.swing.JLabel pieceLabelSecondPlayer4;
    private javax.swing.JLabel pieceLabelSecondPlayer5;
    private javax.swing.JLabel pieceLabelSecondPlayer6;
    private javax.swing.JLabel pieceLabelSecondPlayer7;
    private javax.swing.JLabel playerTurnLabel;
    private javax.swing.JButton rulesButton;
    private javax.swing.JButton saveAndLeaveButton;
    private java.awt.Label secondPlayerLabelName;
    private javax.swing.JLabel secondPlayerTitleLabel;
    private javax.swing.JButton throwDiceButton;
    // End of variables declaration//GEN-END:variables

}

