/*
 * Issue #27 - View Manager.
 * Jimena Gdur Vargas - B93250.
 * Álvaro Miranda Villegas - B84964.
 * Ronald Palma Villegas - B95811.
 */
package view;

import java.awt.BorderLayout;
import java.awt.FlowLayout;
import java.awt.Font;
import java.awt.LayoutManager;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 * Displays game rules.
 * @author Mauricio Palma
 */
public class ShowRules extends javax.swing.JPanel
{
    /**
     * Creates new form ShowRules
     */
    public ShowRules() {
        initComponents();
    }
    /**
     * Creates new frame with game rules.
     */
    public void showRules(){
        //UrRulesModel rules = new UrRulesModel(); // TODO: is this okay?
        JFrame frame = new JFrame("Rules");        
        JPanel panel = new JPanel();
        LayoutManager layout = new FlowLayout();
        panel.setLayout(layout);     
        final JLabel title = new JLabel();
        title.setFont(new Font("Century Schoolbook", 1, 36));
        //title.setText(rules.getRules()[0]);
        title.setText("Some serious rules over here...");
        panel.add(title);    
        /*for (int index = 1; index < rules.getLength(); index++) {
            final JLabel label = new JLabel();
            label.setFont(new Font("Century Schoolbook", 0, 18));
            label.setText(rules.getRules()[index]);
            panel.add(label);
        }*/
        frame.getContentPane().add(panel, BorderLayout.CENTER);   
        frame.setSize(600, 420);      
        frame.setLocationRelativeTo(null);  
        frame.setVisible(true);
        frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        frame.setResizable(false);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
