/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import java.awt.event.ActionListener;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author Alvaro Miranda
 */
public class UrDiceViewPanel extends javax.swing.JPanel {

    ImageIcon diceState1 = new ImageIcon("images/result_0_1.png");
    ImageIcon diceState2 = new ImageIcon("images/result_1_1.png");
    JLabel diceLabelsArray[] = new JLabel[4];
    
    /**
     * Creates new form UrDiceViewPanel
     */
    public UrDiceViewPanel() {
        initComponents();
        //this.setLocationRelativeTo(null);
        diceLabelsArray[0] = dice1;
        diceLabelsArray[1] = dice2;
        diceLabelsArray[2] = dice3;
        diceLabelsArray[3] = dice4;
        dice1.setIcon(diceState1);
        dice2.setIcon(diceState1);
        dice3.setIcon(diceState1);
        dice4.setIcon(diceState1);
    }

    public void showThrow(int rollResult)
    {
        for(int index = 0; index < rollResult; index++){
            diceLabelsArray[index].setIcon(diceState2);
        }
    }
    
    public void cleanDice()
    {
         dice1.setIcon(diceState1);
         dice2.setIcon(diceState1);
         dice3.setIcon(diceState1);
         dice4.setIcon(diceState1);
    }
    
    public void setMoves(int rollResult)
    {
        String movesResult = String.valueOf(rollResult);
        moves.setText(movesResult);
    }
    
    public void addDiceListener(ActionListener listenForThrowDice)
    {
        throwDice.addActionListener(listenForThrowDice); 
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dice1 = new javax.swing.JLabel();
        dice2 = new javax.swing.JLabel();
        dice3 = new javax.swing.JLabel();
        dice4 = new javax.swing.JLabel();
        throwDice = new javax.swing.JButton();
        moves = new javax.swing.JLabel();

        dice1.setText("dice1");

        dice2.setText("dice2");

        dice3.setText("dice3");

        dice4.setText("dice4");

        throwDice.setText("Throw Dice");

        moves.setText("Number of moves");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(throwDice)
                .addGap(18, 18, 18)
                .addComponent(moves)
                .addContainerGap(179, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(9, 9, 9)
                    .addComponent(dice1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(dice2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(dice3, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(dice4, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(17, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(231, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(throwDice)
                    .addComponent(moves))
                .addGap(46, 46, 46))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(110, 110, 110)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                        .addComponent(dice2, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(dice1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(dice3, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(dice4, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(111, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dice1;
    private javax.swing.JLabel dice2;
    private javax.swing.JLabel dice3;
    private javax.swing.JLabel dice4;
    private javax.swing.JLabel moves;
    private javax.swing.JButton throwDice;
    // End of variables declaration//GEN-END:variables
}
