/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

/**
 *
 * @author Mauricio Palma
 */
public class WinnerView extends javax.swing.JPanel {

    /**
     * Creates new form WinnerViewPanel
     */
    public WinnerView() {
        initComponents();
    }

     /**
     * Method that allows to set the id of the plaer who won the match
     * @param playerID The id that will be printed on the screen
     */
    public void setwinnerPlayerText(int playerID){
        winnerText.setText("Player: " + playerID + " wins!");
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        congratulationsTextPanel = new javax.swing.JPanel();
        congratulationsText = new javax.swing.JLabel();
        winnerTextPanel = new javax.swing.JPanel();
        winnerText = new javax.swing.JLabel();

        congratulationsTextPanel.setBackground(new java.awt.Color(153, 153, 153));

        congratulationsText.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        congratulationsText.setText("Congratulations!");

        javax.swing.GroupLayout congratulationsTextPanelLayout = new javax.swing.GroupLayout(congratulationsTextPanel);
        congratulationsTextPanel.setLayout(congratulationsTextPanelLayout);
        congratulationsTextPanelLayout.setHorizontalGroup(
            congratulationsTextPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, congratulationsTextPanelLayout.createSequentialGroup()
                .addContainerGap(312, Short.MAX_VALUE)
                .addComponent(congratulationsText)
                .addGap(306, 306, 306))
        );
        congratulationsTextPanelLayout.setVerticalGroup(
            congratulationsTextPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(congratulationsTextPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(congratulationsText)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        winnerTextPanel.setBackground(new java.awt.Color(153, 153, 153));

        winnerText.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        winnerText.setText("Who won?");

        javax.swing.GroupLayout winnerTextPanelLayout = new javax.swing.GroupLayout(winnerTextPanel);
        winnerTextPanel.setLayout(winnerTextPanelLayout);
        winnerTextPanelLayout.setHorizontalGroup(
            winnerTextPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(winnerTextPanelLayout.createSequentialGroup()
                .addGap(381, 381, 381)
                .addComponent(winnerText)
                .addContainerGap(396, Short.MAX_VALUE))
        );
        winnerTextPanelLayout.setVerticalGroup(
            winnerTextPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, winnerTextPanelLayout.createSequentialGroup()
                .addContainerGap(121, Short.MAX_VALUE)
                .addComponent(winnerText)
                .addGap(95, 95, 95))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(congratulationsTextPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(winnerTextPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(congratulationsTextPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 219, Short.MAX_VALUE)
                .addComponent(winnerTextPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(125, 125, 125))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel congratulationsText;
    private javax.swing.JPanel congratulationsTextPanel;
    private javax.swing.JLabel winnerText;
    private javax.swing.JPanel winnerTextPanel;
    // End of variables declaration//GEN-END:variables
}
