/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author Mauricio Palma
 */
public class WinnerView extends javax.swing.JFrame {

    /**
     * Creates new form WinnerView
     */
    public WinnerView() {
        initComponents();
    }

    /**
     * Method that allows to set the id of the plaer who won the match
     * @param playerID The id that will be printed on the screen
     */
    public void setwinnerPlayerText(int playerID){
        winnerText.setText("Player: " + playerID + " wins!");
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        congratulationsTextPanel = new javax.swing.JPanel();
        congratulationsText = new javax.swing.JLabel();
        winnerTextPanel = new javax.swing.JPanel();
        winnerText = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        congratulationsTextPanel.setBackground(new java.awt.Color(153, 153, 153));

        congratulationsText.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        congratulationsText.setText("Congratulations!");

        javax.swing.GroupLayout congratulationsTextPanelLayout = new javax.swing.GroupLayout(congratulationsTextPanel);
        congratulationsTextPanel.setLayout(congratulationsTextPanelLayout);
        congratulationsTextPanelLayout.setHorizontalGroup(
            congratulationsTextPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, congratulationsTextPanelLayout.createSequentialGroup()
                .addContainerGap(196, Short.MAX_VALUE)
                .addComponent(congratulationsText)
                .addGap(177, 177, 177))
        );
        congratulationsTextPanelLayout.setVerticalGroup(
            congratulationsTextPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(congratulationsTextPanelLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(congratulationsText)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        winnerTextPanel.setBackground(new java.awt.Color(153, 153, 153));

        winnerText.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        winnerText.setText("Who won?");

        javax.swing.GroupLayout winnerTextPanelLayout = new javax.swing.GroupLayout(winnerTextPanel);
        winnerTextPanel.setLayout(winnerTextPanelLayout);
        winnerTextPanelLayout.setHorizontalGroup(
            winnerTextPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(winnerTextPanelLayout.createSequentialGroup()
                .addGap(263, 263, 263)
                .addComponent(winnerText)
                .addContainerGap(286, Short.MAX_VALUE))
        );
        winnerTextPanelLayout.setVerticalGroup(
            winnerTextPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, winnerTextPanelLayout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addComponent(winnerText)
                .addGap(45, 45, 45))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(winnerTextPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(congratulationsTextPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(congratulationsTextPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81)
                .addComponent(winnerTextPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(95, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * {@inheritDoc}
     * Main method that starts graphic aspects of WinnerView
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WinnerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WinnerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WinnerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WinnerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WinnerView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel congratulationsText;
	
    private javax.swing.JPanel congratulationsTextPanel;
    private javax.swing.JLabel winnerText;
    private javax.swing.JPanel winnerTextPanel;
    // End of variables declaration//GEN-END:variables
}
